name: Serverless PR
on:
  pull_request:
    branches:
      # This is the name of the primary branch, which may be `main` for newer repos.
      - main

env:
  # Update this to the location of your distributor root directory if different:
  DISTRIBUTOR_ROOT: "distributor"

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Serverless PR handler
    outputs:
      # Add extra outputs here to match any additions to the matched patterns in the filter step below.
      distributor_incoming: ${{ steps.filter.outputs.distributor_incoming }}
    steps:
      - name: Check for changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          list-files: shell
          filters: |
            distributor_incoming:
              - added: '${{ env.DISTRIBUTOR_ROOT }}/logs/*/incoming/*'
            distributor_private:
              - '${{ env.DISTRIBUTOR_ROOT }}!(/logs/*/incoming/*)'

      - name: Detect distributor structure changes
        if: steps.filter.outputs.distributor_private == 'true'
        run: |
          for i in ${{ steps.filter.outputs.distributor_private_files }}; do
            echo "::error file=${i}::Modified protected distributor structure"
          done
          exit 1

# Run this job only when we've detected a distributor checkpoint PR
  distributor_validator:
    needs: changes
    if: ${{ needs.changes.outputs.distributor_incoming == 'true' }}
    runs-on: ubuntu-latest
    name: Handle distributor PR
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Combine witness signatures (dry run)
        id: combine_witness_signatures_dry_run
        uses: google/trillian-examples/serverless/deploy/github/distributor/combine_witness_signatures@HEAD
        with:
            distributor_dir: './distributor'
            config: './distributor/config.yaml'
            dry_run: true
      # OPTIONAL: Store PR number (only needed if we're using the automerge action below)
      - id: save_metadata
        name: Save PR number
        run: |
          D=$(mktemp -d)/pr_metadata
          mkdir -p ${D}
          echo ${{ github.event.number }} > ${D}/NR
          echo "metadata_dir=${D}" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v3
        with:
          name: pr_metadata
          path: ${{ steps.save_metadata.outputs.metadata_dir }}
      # End OPTIONAL.

