name: Integrate Incoming Checkpoints
on:
  push:
    branches:
      # This is the name of the primary branch, which may be `main` for newer repos.
      - main
  workflow_run:
    workflows: ["Automerge PR"]
  workflow_dispatch:

env:
  # Update this to the location of your distributor root directory if different:
  DISTRIBUTOR_ROOT: "distributor"

jobs:
  combine_witness_sigs:
    runs-on: ubuntu-latest
    name: Combine witness signatures
    steps:
    - uses: actions/checkout@v2
    # Attempt to combine witness signatures with the log checkpoint.
    - name: Combine witness signatures
      id: combine_witness_signatures
      uses: google/trillian-examples/serverless/deploy/github/distributor/combine_witness_signatures@HEAD
      with:
          distributor_dir: '${{ env.DISTRIBUTOR_ROOT }}'
          config: '${{ env.DISTRIBUTOR_ROOT }}/config.yaml'
    # Update log index.
    - name: Update logs index
      id: update_logs_index
      uses: google/trillian-examples/serverless/deploy/github/distributor/update_logs_index@HEAD
      with:
          distributor_dir: '${{ env.DISTRIBUTOR_ROOT }}'
          config: '${{ env.DISTRIBUTOR_ROOT }}/config.yaml'
          output: '${{ env.DISTRIBUTOR_ROOT }}/logs/README.md'
    # Commit any changes back to distributor repo.
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_user_name: Serverless Bot
        commit_user_email: actions@github.com
        commit_author: Serverless Bot <actions@github.com>
        commit_message: Automatically merge witness signatures

